/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#0a7ea4';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    text: '#11181C',
    textInWhite: '#000000',
    background: '#fff',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    orange: '#FFA500',
    gray: 'gray',
    primary: '#007AFF',
    card: '#F2F2F2',
    inputBackground: '#FFFFFF',
    red: '#FF3B30',
    green: '#34C759',
    settingsButton: '#42A5F5',
    settingsIcon: '#000000',
    groupsButton: '#FF9800',
    chatButton: '#42A5F5',
    chatAvatar: '#42A5F5',
    groupAvatar: '#FF9800',
    separator: '#444444',
    addProjectBorder: '#555555',
    projectCardShadow: '#000000',
    progressBarBackground: '#E0E0E0',
    progressBarFill: '#42A5F5',
    progressBarText: '#11181C',
    memberAvatarBackground: '#E0E0E0',
    memberAvatarText: '#11181C',
    memberCountBackground: '#F2F2F2',
    memberCountText: '#11181C',
  },
  dark: {
    text: '#ECEDEE',
    textInWhite: '#000000',
    background: '#151718',
    tint: tintColorDark,
    icon: '#9BA1A6',
    tabIconDefault: '#9BA1A6',
    tabIconSelected: tintColorDark,
    orange: '#FFA500',
    gray: 'gray',
    primary: '#007AFF',
    card: '#282828',
    inputBackground: '#3A3A3A',
    red: '#FF453A',
    green: '#32D74B',
    settingsButton: '#42A5F5',
    settingsIcon: '#FFFFFF',
    groupsButton: '#FF9800',
    chatButton: '#0066cc',
    chatAvatar: '#42A5F5',
    groupAvatar: '#FF9800',
    separator: '#444444',
    addProjectBorder: '#555555',
    projectCardShadow: '#000000',
    progressBarBackground: '#3A3A3A',
    progressBarFill: '#42A5F5',
    progressBarText: '#ECEDEE',
    memberAvatarBackground: '#3A3A3A',
    memberAvatarText: '#ECEDEE',
    memberCountBackground: '#282828',
    memberCountText: '#ECEDEE',
  },
};
